
version: '2.40'
services:
  web:
    image:
    ports: 3000
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - server
  server:
    ports: 
      - '3000'
      - '8000:80'
    volumes:
      - .:/app
  
